<div class="row">
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand">Money Tracking</a>
            </div>
        </div>
    </nav>
    <div class="col-sm-8"><h2>Agregar categoría</h2></div>

    <div class="col-sm-6">
        <form action="<?php echo APP_URL . "categorias/agregar"; ?>" method="POST">
            <p>
                <label for="name">Nombre</label>
                <input type="text" name="name" class="form-control">
            </p>
            <p>
                <input class="btn-primary" type="submit" value="Guardar categoria"
                       onclick="if(!confirm('¿Desea completar la acción?')) return false;">
            </p>
        </form>
    </div>
</div>
</div>


