<div class="row">
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand">Money Tracking</a>
            </div>
        </div>
    </nav>
    <div class="col-sm-8"><h2>Editar cuenta</h2></div>
    <div class="col-sm-6">
        <form action="<?php echo APP_URL . "cuentas/editar"; ?>" method="POST">
            <input type="hidden" name="id" value="<?php echo $this->cuenta["id"]; ?>">
            <p>
                <label for="name">Nombre</label>
                <input type="text" name="name" value="<?php echo $this->cuenta["name"]; ?>" class="form-control">
            </p>
            <p>
                <input type="submit" value="Guardar cuenta" class="btn-primary add"
                       onclick="if(!confirm('¿Desea completar con la acción?')) return false;">
            </p>
        </form>
    </div>
</div>
</div>